server {
    port 8080; 
    host localhost;
    root website; 
    index index.html;
    autoindex on;
    client_max_body_size 2000000;

       location /upload/ {
            root srcs;
            autoindex on;
            allow_methods GET POST DELETE;
            return 301 /test
        }
        location /upload/ABERRANT/test/ {   
            
            autoindex on;
            allow_methods GET POST DELETE;
        }
 
        location website/upload/test/ {
            autoindex on;
            allow_methods GET POST DELETE;
        }


        location /test {
            root ./var/www/main/test;
            autoindex off;
            allow_methods GET DELETE;
        }
    error_page 404 pages_errors/404.html;
    error_page 403 pages_errors/403.html;
    error_page 500 /pages_errors/500.html;
}
server {
    port 6565; 
    host 127.0.0.1;
    root website;
    autoindex on;
    index index.txt;
    client_max_body_size 10000000;

        location /test {
            root ./var/www/main/test;
            autoindex off;
            allow_methods GET DELETE;
        }
    error_page 404 /pages_error/404.html;
}
