server {
    port 8080; 
    host 127.0.0.1;
    server_name first;
    root website/;
    index index.html;
    autoindex on;
    client_max_body_size 2000000;
    upload_dir up/;
    allowed_methods GET POST;
        location /cgi/ {
            allowed_methods GET POST;
            cgi_pass .py /usr/bin/python3;
        }
        location /cgi/nofanizz/ {
            return 404;
        }
    error_page 404 403 500 pages_errors/500.html;
}
